// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpfxeuijerwuwqntxypy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwZnhldWlqZXJ3dXdxbnR4eXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5MzYyNjQsImV4cCI6MjA1MjUxMjI2NH0.rNFKwsZRhH_8aYAJv_nRqCBiYOw19r5EMQNVFd-QG7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
